### ISSUE TITLE
Some annotations in video ./data/training/zudeWqL9ALU does not have any matching proposal

### ISSUE THREAD

**Issue by existence23** [salesforce/densecap#10]
When I start to train the videos, some of the sample videos shows the message that "Some annotations in video ./data/training/zudeWqL9ALU does not have any matching proposal" but some others not. Is there any reason why this happened?
And every time I tried to train these, it always got stuck in some places and cannot continue? It this might because of there is no enough space for this calculation?

**Comment by LuoweiZhou** [comment]
@existence23 some extreme short segments might not match any of the temporal proposals (i.e., tIoU below a threshold). For the second problem, we are trying to solve it. It should be related to this: https://github.com/LuoweiZhou/densecap/issues/3#issuecomment-495360947

**Comment by LuoweiZhou** [comment]
@existence23 could you tell me more about your OS version, graphics card type, cuda version, cudnn version, and pytorch version?

**Comment by existence23** [comment]
Hi, my OS version is Ubuntu 16.04, graphics card type: "01:00.0 VGA compatible controller: NVIDIA Corporation Device 1e07 (rev a1)" 
cuda 9.0 and cudnn 7.4.2 and pytorch 1.1.0

**Comment by LuoweiZhou** [comment]
@existence23  Our code has not been tested on PyTorch 1.1.0. Can you try PyTorch 0.4 instead? Also, could you run `nvidia-smi` and post your screenshot here?

**Comment by existence23** [comment]
![Screenshot from 2019-05-25 18-28-06](https://user-images.githubusercontent.com/35708927/58375160-e9ce4f00-7f1a-11e9-9ab3-45d8750ee929.png)
Thanks for your reply! I'll try PyTorch 0.4 later.
