### ISSUE TITLE
error with CUDA multiprocessing

### ISSUE THREAD

**Issue by rishabh2301** [salesforce/densecap#11]
Hi, Thank you very much for the code. I am trying to train the model with the yc2 dataset. I am continuously getting this - ''RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method" after searching through pytorch forum I got to know that this error occurs because the tensor is not transferred to GPU and in the dataloader , pin_memory argument should be set to True. I did that but still getting the same error. Don't know what is the issue. According to the requirements suggested by you, I am running this with PyTorch - 0.4.0., cudnn v7.2.1 and cuda 9.2. Can you please help if you have any insight with this, thank you very much.

**Comment by LuoweiZhou** [comment]
@rishabh2301 we believe this is a device-related issue. We have tested the code on 1080Ti / Titan Xp / V100 etc. and cannot reproduce the same problem. You can refer to a similar issue [here](https://github.com/LuoweiZhou/densecap/issues/3).
As an alternative, you might want to disable the multiprocessing. This might slow things down at the first run, but once you've [saved](https://github.com/salesforce/densecap/blob/master/data/anet_dataset.py#L188) all the positive/negative segment, you're good.

**Comment by rishabh2301** [comment]
@LuoweiZhou  thank you for your response. I edited the anet_dataset.py script with this : 

from torch.multiprocessing import Pool, Process, set_start_method, cpu_count
try:
     set_start_method('spawn')
except RuntimeError:
    pass

for importing the multiprocessing dependencies, and got rid of the previous error. However now I am getting a new error on training - "RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCCachingAllocator.cpp:625
"

![error](https://user-images.githubusercontent.com/30569562/59492619-ee53ab00-8ebb-11e9-9d00-c86a16441244.png)

but the GPU is not getting out of memory  

![nvidia-smi](https://user-images.githubusercontent.com/30569562/59492920-98cbce00-8ebc-11e9-98d4-5c5ed11918b4.png)

I assumed it may be due to the batch size of 14 and ran the code with a batch size of 1 than also getting the error, is it due to multiprocessing?  If you may have any suggestions, please let me know. Thank you very much.

**Comment by rishabh2301** [comment]
So after researching a while now got to know that "there's a bug in python multiprocessing that might keep the child process hanging around, as zombie processes and It is not even visible to nvidia-smi" which is causing the cuda run out of memory error. The solution to this is to kill subprocesses manually which are completed, with kill -9 [pid] . For now I have disabled the multi-processing and the code is working fine, though it is slow. More details about this error can be found here  - https://discuss.pytorch.org/t/pytorch-doesnt-free-gpus-memory-of-it-gets-aborted-due-to-out-of-memory-error/13775/14?u=rishabh_saraf

**Comment by LuoweiZhou** [comment]
@rishabh2301 thank you for the info! Great to know that you've figured out the reason. Just to make sure you save the positive/negative segments at the first run.

**Comment by entingsung** [comment]
> So after researching a while now got to know that "there's a bug in python multiprocessing that might keep the child process hanging around, as zombie processes and It is not even visible to nvidia-smi" which is causing the cuda run out of memory error. The solution to this is to kill subprocesses manually which are completed, with kill -9 [pid] . For now I have disabled the multi-processing and the code is working fine, though it is slow. More details about this error can be found here - https://discuss.pytorch.org/t/pytorch-doesnt-free-gpus-memory-of-it-gets-aborted-due-to-out-of-memory-error/13775/14?u=rishabh_saraf

Hi @rishabh2301 ! I encountered the same problem as you, and trying to use your solution to address it. But I am wondering how do you know which processes should be killed. Could you please give more detail about the solution? Thank you very much.

**Comment by awkrail** [comment]
Hello.

I met the same error, and I solved this problem by removing the multiprocessing as follow:
(original)
```python
            with multiprocessing.Pool(1) as pool:
                results = [None]*len(raw_data)
                vid_idx = 0
                import ipdb; ipdb.set_trace()
                for vid, val in raw_data.items():
                    annotations = val['annotations']
                    for split_path in split_paths:
                        if val['subset'] in split and os.path.isfile(os.path.join(split_path, vid + '_bn.npy')):
                            results[vid_idx] = pool.apply_async(_get_pos_neg,
                                         (split_path, annotations, vid,
                                          slide_window_size, frame_to_second[vid], anc_len_all,
                                          anc_cen_all, pos_thresh, neg_thresh))
                            vid_idx += 1
                results = results[:vid_idx]
                for i, r in enumerate(results):
                    results[i] = r.get()
```
(removing multiprocessing)
```python
            results = [None]*len(raw_data)
            vid_idx = 0
            for vid, val in raw_data.items():
                annotations = val['annotations']
                for split_path in split_paths:
                    if val['subset'] in split and os.path.isfile(os.path.join(split_path, vid + '_bn.npy')):
                        #results[vid_idx] = pool.apply_async(_get_pos_neg,
                        #                (split_path, annotations, vid,
                        #                 slide_window_size, frame_to_second[vid], anc_len_all,
                        #                 anc_cen_all, pos_thresh, neg_thresh))
                        results[vid_idx] = _get_pos_neg(
                          split_path, annotations, vid,
                          slide_window_size, frame_to_second[vid], anc_len_all,
                          anc_cen_all, pos_thresh, neg_thresh
                        )
                        vid_idx += 1
            results = results[:vid_idx]
            for i, r in enumerate(results):
                results[i] = r.get()
```
Note that this modification makes computation too slow, but it works in my case.

**Comment by entingsung** [comment]
Hello,

Thanks for your reply and solution!!!
It’s so kind of you.
I’ll try it! Many thanks!!





Taichi Nishimura <notifications@github.com>於 2020年7月17日 週五，下午12:26寫道：
