### ISSUE TITLE
Want to try hour video

### ISSUE THREAD

**Issue by hollowgalaxy** [salesforce/densecap#12]
Do I need to modify anything to get the captions for the entire hour? I seem to be getting only the first 300 or so seconds.

**Comment by LuoweiZhou** [comment]
@hollowgalaxy you can increase the arg [--slide_window_size] (in second) to accept longer video input. We assume the current inputs are sampled at [~2 fps](https://github.com/salesforce/densecap/blob/master/scripts/train.py#L69), so for a one-hour long video, you will need to have a ~7200-frame long input (this might go beyond your GPU memory capacity). We'd suggest you take a look at this [repo](https://github.com/LuoweiZhou/anet2016-cuhk-feature) for feature extraction.

**Comment by hollowgalaxy** [comment]
Thank you, what I was looking for

**Comment by hollowgalaxy** [comment]
For `sliding_window_size` would an 1 minute long video be set to 60 or 120 (since the ~2fps)?

**Comment by LuoweiZhou** [comment]
@hollowgalaxy if your videos have fewer than 480 sampled frames, they will be [zero padded](https://github.com/salesforce/densecap/blob/master/data/anet_dataset.py#L199) to 480at the end during training. During inference, it depends on whether you're learning the [gate](https://github.com/salesforce/densecap/blob/master/data/anet_test_dataset.py#L64) or not.

**Comment by hollowgalaxy** [comment]
Sorry I may have misconstrued my question. 480 represents seconds in a video? Or number of frames outputed from numpy video features? For the latter, if a video created with outer dim being 480 for resnet and bn, would that fit in its entirety.

**Comment by LuoweiZhou** [comment]
Latter. The part exceeds 480 will be [trimmed](https://github.com/salesforce/densecap/blob/master/data/anet_dataset.py#L202).
