### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by guillaumevr** [salesforce/densecap#13]
Hi,
your website http://youcook2.eecs.umich.edu seems to be down
Could you do something?
thx

**Comment by LuoweiZhou** [comment]
@guillaumevr it's back on now.

**Comment by maitreya987** [comment]
Hi, 
the website seems to be down again.
Could you please fix it?

**Comment by LuoweiZhou** [comment]
@maitreya987 sorry there was an issue with the server power backup. We will replace the failed backup asap.

**Comment by LuoweiZhou** [comment]
@maitreya987 it's back on.

**Comment by maitreya987** [comment]
Thanks!
