### ISSUE TITLE
Question about the sampling rate calculation.

### ISSUE THREAD

**Issue by hollowgalaxy** [salesforce/densecap#14]
First question, in the csv with duration and frames. Is the frames number the total number of frames in the video, or is it the number of frames created by the _bn.shape[0]?

Second questions.  For the calculation in [here](https://github.com/salesforce/densecap/blob/9eae43ea4819a169c719208c5262a834e20e6b34/scripts/test.py#L152). Why is are you flooring the rate as opposed to using ceil for the yc2 dataset?

Third question. Why do `(duration/frame)*ceil(0.5*frame/duration)`, if the model is outputting position in frame numbers.... Then given that units of 0.5 is frames/seconds -> Wouldn't changing the equation to get the correct time  to this instead to do `0.5*(duration/frame)` meaning you convert to duration, to match the units

**Comment by LuoweiZhou** [comment]
@hollowgalaxy please see the followings.
1. The total number of frames in the video.
2. Please refer to our feature extraction code [here](https://github.com/LuoweiZhou/anet2016-cuhk-feature). ANet is processed with an older version of the repo and yc2 is processed with the latest code which had a minor change regarding the sampling approach.
3. We formulate the frame rate to match the frame rate we used in [feature extraction](https://github.com/LuoweiZhou/anet2016-cuhk-feature/blob/master/pyActionRec/video_proc.py#L85).
