### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by Unispac** [salesforce/densecap#17]
Hi.
I want to know how to extract the feature for unseen videos...
Are there any pretrained feature extraction model?
Thanks...

**Comment by LuoweiZhou** [comment]
Hi @Unispac, please refer to this issue for details: https://github.com/salesforce/densecap/issues/5 and let me know if you have any further questions.

**Comment by Unispac** [comment]
Thanks!!!
I just see...
Sorry to bother you.

**Comment by LuoweiZhou** [comment]
No problem, good to know that. Thanks!
