### ISSUE TITLE
Error when loading yc2 model

### ISSUE THREAD

**Issue by FrankChJ** [salesforce/densecap#19]
Hi, when I tried to use the pretrained y2c model, there seems be something wrong
when loading the model for yc2...

RuntimeError: Error(s) in loading state_dict for ActionPropDenseCap:                                                                                                                                   Missing key(s) in state_dict: "prop_out.16.0.weight", "prop_out.16.0.bias", "prop_out.16.0.r                                                                                           unning_mean", "prop_out.16.0.running_var", "prop_out.16.1.weight", "prop_out.16.2.weight", "prop_out                                                                                           .16.2.bias", "prop_out.16.2.running_mean", "prop_out.16.2.running_var", "prop_out.16.3.weight", "pro                                                                                           p_out.16.4.weight", "prop_out.16.4.bias", "prop_out.16.4.running_mean", "prop_out.16.4.running_var",                                                                                            "prop_out.16.6.weight", "prop_out.16.6.bias", "prop_out.16.6.running_mean", "prop_out.16.6.running_                                                                                           var", "prop_out.16.7.weight", "prop_out.16.7.bias", "prop_out.17.0.weight", "prop_out.17.0.bias", "p                                                                                           rop_out.17.0.running_mean", "prop_out.17.0.running_var", "prop_out.17.1.weight", "prop_out.17.2.weig                                                                                           ht", "prop_out.17.2.bias", "prop_out.17.2.running_mean", "prop_out.17.2.running_var", "prop_out.17.3                                                                                           .weight", "prop_out.17.4.weight", "prop_out.17.4.bias", "prop_out.17.4.running_mean", "prop_out.17.4                                                                                           .running_var", "prop_out.17.6.weight", "prop_out.17.6.bias", "prop_out.17.6.running_mean", "prop_out                                                                                           .17.6.running_var", "prop_out.17.7.weight", "prop_out.17.7.bias".                                                                                                                                      size mismatch for prop_out.1.1.weight: copying a param with shape torch.Size([1024, 1, 3]) f                                                                                           rom checkpoint, the shape in current model is torch.Size([1024, 1, 2]).                                                                                                                                size mismatch for prop_out.2.1.weight: copying a param with shape torch.Size([1024, 1, 5]) f                                                                                           rom checkpoint, the shape in current model is torch.Size([1024, 1, 3]).                                                                                                                                size mismatch for prop_out.3.1.weight: copying a param with shape torch.Size([1024, 1, 7]) f                                                                                           rom checkpoint, the shape in current model is torch.Size([1024, 1, 4]).                                                                                                                                size mismatch for prop_out.4.1.weight: copying a param with shape torch.Size([1024, 1, 9]) f                                                                                           rom checkpoint, the shape in current model is torch.Size([1024, 1, 5]).                                                                                                                                size mismatch for prop_out.5.1.weight: copying a param with shape torch.Size([1024, 1, 11])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 7]).                                                                                                                               size mismatch for prop_out.6.1.weight: copying a param with shape torch.Size([1024, 1, 15])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 9]).                                                                                                                               size mismatch for prop_out.7.1.weight: copying a param with shape torch.Size([1024, 1, 21])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 11]).                                                                                                                              size mismatch for prop_out.8.1.weight: copying a param with shape torch.Size([1024, 1, 27])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 15]).                                                                                                                              size mismatch for prop_out.9.1.weight: copying a param with shape torch.Size([1024, 1, 33])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 21]).                                                                                                                              size mismatch for prop_out.10.1.weight: copying a param with shape torch.Size([1024, 1, 41])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 29]).                                                                                                                             size mismatch for prop_out.11.1.weight: copying a param with shape torch.Size([1024, 1, 49])                                                                                            from checkpoint, the shape in current model is torch.Size([1024, 1, 41]).
--

**Comment by LuoweiZhou** [comment]
Hi @FrankChJ what's your command? Please make sure you're loading the yc2 config file.

**Comment by FrankChJ** [comment]
@LuoweiZhou 
I am performing the test algorithm on outer data.
this is my command :
"""
python3 test.py --cfgs_file cfgs/comp.yml  \
    --batch_size 1 --start_from results/yc2-2L-e2e-mask/model_epoch_19.t7 --id comp_yc2 \
    --val_data_folder comp --learn_mask --gated_mask --dataset yc2 --cuda 
"""
And actually, in the config file comp.yml, I refer to some yc2 data file to build the dictionary.
this is comp.yml:
"""
dataset: "comp"                                                                                      
dataset_file: "./data/yc2/yc2_annotations_trainval.json"                                             densecap_references: ["./data/yc2/val_yc2.json"]                                                     
source_file: "./data/comp/comp.json"                                                                 
feature_root: "./data/"                                                                      
dur_file: "./data/comp/comp.csv"                                                                     
kernel_list: [1, 2, 3, 4, 5, 7, 9, 11, 15, 21, 29, 41, 57, 71, 111, 161, 211, 251]
"""

**Comment by FrankChJ** [comment]
Oh, I guess I get the point. 
The kernel_list in yc2 is different from that in anet.
Thanks for replying!!!
