### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'append'

### ISSUE THREAD

**Issue by jasonseu** [salesforce/densecap#20]
https://github.com/salesforce/densecap/blob/1f6189c90ae8d7fd006c6d2394e9553bf1a614ac/model/action_prop_dense_cap.py#L467

Hey, I think you have made a mistake here. The variable pred_results is the object of np.ndarray, which have no append method.

**Comment by LuoweiZhou** [comment]
Hi @jasonseu, thank you for the feedback. It should be `pred_results[0] = np.array([0, min(original_frame_len, T), pos_thresh])` instead and seems that loop is never executed. Will fix.

**Comment by jasonseu** [comment]
@LuoweiZhou Yes, I think so, otherwise your code will not run successfully.
