### ISSUE TITLE
Model training with a single 2080 Ti

### ISSUE THREAD

**Issue by ghost** [salesforce/densecap#22]
Hi and thanks for the code.

I would like to run the `train.py` script on a single 2080 Ti GPU, with 10 GB of free memory ram.  I tried batch sizes of down to `1`, but I still get Cuda out of memory error. Is there any workaround to the problem? Or should I consider training on two GPUs? I am using the ActivityNet dataset.

I use this command to run the training script:
```
python3 scripts/train.py --cfgs_file cfgs/anet.yml --checkpoint_path ./checkpoint/e2e-masked --world_size 1 --batch_size 1 | tee log/e2e-masked
```
Thanks,
Ali

**Comment by LuoweiZhou** [comment]
Hi @aligholami, can you confirm that you have set `--cuda` in your script? Also, since you are using RTX GPUs, I assume you're using CUDA 10 and PyTorch 1.0+? We have a note here regarding this: https://github.com/salesforce/densecap#requirements-recommended

**Comment by ghost** [comment]
@LuoweiZhou Yes, I add the ``--cuda`` and forgot to put it in the script above. I am using CUDA 10 and PyTorch 1.2 and yes, I read the notes in that link. Do you think the problem is because of using a different PyTorch version?

**Comment by LuoweiZhou** [comment]
@aligholami Highly likely. I'd recommend you try it on non-RTX GPUs with PyTorch 0.4 and see if you get the same error.

**Comment by AnukritiSinghh** [comment]
Hello @gholomia can you please tell me how'd you write the model name e2e-masked as $id in the checkpoint? For where did you get e2e-masked?
