### ISSUE TITLE
Sorry ,the speed for downloading the features is too slowly.

### ISSUE THREAD

**Issue by a1391651300** [salesforce/densecap#24]
Sorry ,the speed for downloading the features is too slowly.Could you please provide the link of  Google Drive or any other way ?
Thank you for your work.Is the pretrained model has been well trained and I can deel with my own video without anymore training?

Thank you ,looking forward yor answer.

**Comment by LuoweiZhou** [comment]
@a1391651300  Could you provide the links that you wish to have on Google Drive?

Yes, as long as you use the same feature extraction code as we provided.
