### ISSUE TITLE
References to feature extraction methods?

### ISSUE THREAD

**Issue by ghost** [salesforce/densecap#26]
Hello and thanks for this great repo.

Could you please provide some reference to the paper/implementations used for feature extraction? I believe there are two major methods for feature extraction:
1. Optical flow BN-Inception feature
2. RGB ResNet-200 feature

Best,
Ali

**Comment by LuoweiZhou** [comment]
You can find it in the last paragraph of [here](https://github.com/salesforce/densecap#annotation-and-feature).
A few related notes are [here](https://github.com/salesforce/densecap/issues/25).

**Comment by ghost** [comment]
Hello.

I appreciate it if you can provide the actual references to the papers that come with this repo. I think it is better that you include them as a part of the repository. I went through the links but found nothing more useful than:
1. Optical flow BN-Inception feature
2. RGB ResNet-200 feature

I wish I knew the title of the papers at least :-)

**Comment by LuoweiZhou** [comment]
It's based on this repo: https://github.com/yjxiong/anet2016-cuhk
