### ISSUE TITLE
detail about sampling in get_pos_and_neg 

### ISSUE THREAD

**Issue by john2019-warwick** [salesforce/densecap#27]
Hi, Luowei, thanks for your work and code provided! Can I ask you a question about detail in the code?
![Screenshot from 2019-11-06 11-35-32](https://user-images.githubusercontent.com/57441325/68295203-c68efa80-0089-11ea-8966-ea70f8f4f3e9.png)
In get_pos_and_neg function of train.py, when computing tIoU, why you use gt_start/sampling_sec, but for the potential proposal, it is not divided by sampling_sec. Based on my understanding, you just focus on the sampled feature every around 0.5s, but if this is the case, why the feature loaded (resnet and optical flow) is complete(every frame)? Also, why you have to calculate the sampling sec for each video? Cannot use fixed 0.5? Thanks!

**Comment by LuoweiZhou** [comment]
The sampling rate does not guarantee to be 0.5s every frame due to int casting: https://github.com/LuoweiZhou/anet2016-cuhk-feature/blob/master/pyActionRec/video_proc.py#L85. Hence, we need to compute it per video.

**Comment by john2019-warwick** [comment]
Thanks! This issue can be closed!
