### ISSUE TITLE
How to convert video into appearence features and optical flow features?

### ISSUE THREAD

**Issue by asafarevich** [salesforce/densecap#3]
I want to test your model on another dataset.

How would I go about converting a video to appearance features and optical features? The provided links for data seem to have that already done. 

Do you have a script saved somewhere that does it, or is there a GitHub repo hiding in the wild?

**Comment by LuoweiZhou** [comment]
Our feature extraction code is based on this repo: https://github.com/yjxiong/anet2016-cuhk

**Comment by asafarevich** [comment]
@LuoweiZhou  I extracted the video features from the caffe model you linked. But the output shape of the layers given by paper does not match the shape of the npy files provided. 
To be more specifically, (N = number of frames), resnet's 'caffe.Flatten_673' gives a shape of [N, 1, 2048] and bn's 'global_pool' gives a shape of [N,10,1024,1,1]. (I tried several videos to confirm this)

Now resnet is not a problem, as I can just np.squeeze, which matches the npy's shape of [N,2048]. But bn inception does not match with shape [N,1024], what do I do with the dimention that has length of 10?

**Comment by LuoweiZhou** [comment]
Hi @Anton-Velikodnyy, for the motion feature, we disable the oversampling, i.e., we only extract the feature from the center crop. This can be done by setting `over_sample=False` when calling `net.predict_single_flow_stack`. You can refer to [here](https://github.com/yjxiong/anet2016-cuhk/blob/master/pyActionRec/utils/io.py) for details on oversampling.

**Comment by LuoweiZhou** [comment]
Since we no longer use the oversampling, it would be better to resize frames for flow extraction to exactly 224x224 (so the center crop is the whole image). This could be done by setting `flow_stack = self.__flow_extractor.extract_flow(frm_stack, flow_frame_size)` where `flow_frame_size = (224, 224)`

**Comment by asafarevich** [comment]
Thank you for the pointers. I set  the flow frame_size to (224,224) and over sample to false. I am not sure why you linked the `flow_stack_oversample` function, because when setting `over_sample=False`, [Given](https://github.com/yjxiong/anet2016-cuhk/blob/1e4e54dc8be77e5389da14eac07eed3236fc52e6/pyActionRec/action_caffe.py#L62) this section of code, `flow_stack_oversample` would not get called for the flow model.

I still get 10 dimention size after making these changes and these https://github.com/salesforce/densecap/issues/5

**Comment by LuoweiZhou** [comment]
The `flow_stack_oversample` function performs the oversampling and generates 10 cropped regions. This accounts for the `[N,*10*,1024,1,1]` output size. If you set `over_sample=False` then we will only pick the center crop of size 224x224.

**Comment by asafarevich** [comment]
My sincerest apologies. I didn't save the file before running the extraction. This part works now.

Are there any other modifications of the anet repo I should be worried with?

**Comment by LuoweiZhou** [comment]
No worries and great to know that it worked out. I made our modified [repo](https://github.com/LuoweiZhou/anet2016-cuhk-feature) public so you can further refer to.
