### ISSUE TITLE
No output 

### ISSUE THREAD

**Issue by rachita-ramesh** [salesforce/densecap#30]
I used the pre-trained model and downloaded the test dataset of youcook2. 
While running test.py file, I'm not getting any output. Any suggestions ?

Thanks in advance

**Comment by LuoweiZhou** [comment]
@rachita-ramesh I assume you mean you did not get the language evaluation outcome? Have you got the result JSON file? If so, then you can run this command separately to better debug: https://github.com/salesforce/densecap/blob/master/scripts/test.py#L216
