### ISSUE TITLE
Import Error for numpy

### ISSUE THREAD

**Issue by rishabh2301** [salesforce/densecap#31]
https://github.com/salesforce/densecap/blob/45b20bb0860b0c5a5fc4878284c1ab0e6892a68f/scripts/test.py#L216

Hi @LuoweiZhou  on testing the code and calling the evaluation scripts you have used python2, but I am constantly getting import error for NumPy. Do you know about this error ? I think somehow it may be related with my NumPy package installed for python 3.7. But I couldn't figure out still. Can you please help.

**Comment by LuoweiZhou** [comment]
@rishabh2301 This usually results from multiple installed Numpy on both python2 and python3. You might want to check where are the packages using `pip show` or `pip3 show`. You may also want to ensure the program is not using numpy outside of the conda environment (i.e., the base env) or the local version.
