### ISSUE TITLE
Ground truth values are 0

### ISSUE THREAD

**Issue by lucky-23** [salesforce/densecap#34]
When I tried to run the test.py I always seem to get the error in the line of eval_proposal_anet.py max_avg_nr_proposals = float(proposals.shape[0]) / video_lst.shape[0]. The error says it cannot be divided by zero. When I checked the ground truth it all turns out to be zero. I cannot understand why there seems to be no ground truth files. I am new to video captioning and python in general.I would be really grateful if you could help me out fix this problem.

**Comment by LuoweiZhou** [comment]
@lucky-23  For event proposal, you may want to check if you have loaded the correct [GT file](https://github.com/salesforce/densecap/blob/2a4bb05b9a22ef025d3a25e34527059b3124c317/tools/eval_proposal_anet.py#L88). Also, your [output file](https://github.com/salesforce/densecap/blob/6ac8cceea7b5f4e4469e5e09e9f434d92841ddf9/scripts/test.py#L231) exists as we adopt an offline evaluation.

**Comment by lucky-23** [comment]
Thanks for replying back. Can you please specify which is the ground truth file? I am confused about it.
Thanks again

**Comment by LuoweiZhou** [comment]
It's here: https://github.com/salesforce/densecap/blob/master/scripts/test.py#L35
You may also want to double check the subset: https://github.com/salesforce/densecap/blob/master/scripts/test.py#L234

**Comment by lucky-23** [comment]
Thanks alot!
