### ISSUE TITLE
Obtained not good result for yc2 validation dataset, how to fix?

### ISSUE THREAD

**Issue by KCbao** [salesforce/densecap#35]
@LuoweiZhou Thank you for your great work. I am trying video captioning on yc2 validation dataset with yc2 e2e pre-trained model, but I didn't get reasonable results. Going through the entire validation dataset took me several hours, so I just set break points in codes to see captions for each video. For example, for video id =  xHr8X2Wpmno, which is a AUTHENTIC Fattoush Salad Recipe (Fattoush Recipe Video), I got captions like 
`(156.0, 202.0, 0.9916355609893799, 'add the pork <unk> ...o the wok'), (147.0, 180.0, 0.9914172291755676, 'add the pork <unk> ...o the wok'), (170.0, 213.0, 0.9912750720977783, 'add the pork <unk> ...o the wok'), (149.0, 181.0, 0.9911263585090637, 'add the pork to the wok'), (165.0, 206.0, 0.9908148646354675, 'add the pork <unk> ...o the wok'), (166.0, 222.0, 0.9906260967254639, 'add the pork <unk> ...o the wok'), (156.0, 211.0, 0.9902746677398682, 'add the pork <unk> ...o the wok'), (152.0, 200.0, 0.9902364611625671, 'add the pork <unk> ...o the wok'),(168.0, 202.0, 0.989440381526947, 'add the pork and ri...o the wok'), (158.0, 206.0, 0.9893548488616943, 'add the pork <unk> ...o the wok')`
I understand your model produces overlapped proposals, but the captions I got don't look reasonable to the salad recipe. 

Below are the configuration file I set for ycs:
```# dataset specific settings for yc2
dataset: "yc2"
dataset_file: "/home/an007936/densecap/data/yc2/yc2_annotations_trainval.json"
feature_root: "/home/an007936/densecap/data/yc2"
densecap_references: ["./data/yc2/val_yc2.json"]
dur_file: "/home/an007936/densecap/data/yc2/yc2_duration_frame.csv"
kernel_list: [1, 3, 5, 7, 9, 11, 15, 21, 27, 33, 41, 49, 57, 71, 111, 161]
densecap_eval_file: './tools/densevid_eval/evaluate.py'
batch_size: 1 
start_from: '/home/an007936/densecap/checkpoint/yc2-2L-e2e-mask/model_epoch_19.t7'
id: 'yc2-2L-e2e-mask-19' 
val_data_folder: 'validation' 
learn_mask: True
gated_mask: True
cuda: True
```
Is this configuration correct? If so, what would be the possible reasons I got these not good captioning results? I am very new to video captioning area, and I greatly appreciate your help on this issue. Thank you!

**Comment by LuoweiZhou** [comment]
@KCbao The difficulty in this task lies in both event localization and caption generation. Hence, an imperfect event localization might result in bad captions. Your config file looks good to me.

As for the evaluation speed, it should not take hours. Make sure you're loading the feature files locally vs. through network (e.g. NFS) as this could greatly affect the speed (you could also bind the feature files into a few *.h5 to make loading faster). Here is our caption output for your reference: https://drive.google.com/drive/folders/1Sm9jixy6FocVG8Lkf3FQdcI7G0I8ZyLk?usp=sharing
